spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/applicationdb
    username: david
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: validate #create-drop #update #validate #none
    properties:
        hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
            lob:
            non_contextual_creation: true
  servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB
  application:
      name: springboot-postgres
  flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
      schemas: applicationdb
server:
    port: 8080
    error:
        include_message: always

